language: csharp
solution: RadDock.sln
install:
  - nuget restore RadDock.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release RadDock.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./RadDock/bin/Release/RadDock.exe
